name: Release

on:
  push:
    branches: [ fork ]
  pull_request:
    branches: [ fork ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  LLVM_SYS_211_PREFIX: /usr/lib/llvm-21

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install Rust
      run: |
        sudo apt-get update
        sudo apt-get install -y cargo rustc
        rustc --version
        cargo --version
    - name: Install LLVM 21
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21 all
    - name: Build release binary
      run: cargo build --release
    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ante
        path: target/release/ante

  build-static-musl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build static musl binary
      run: .github/build.sh
    - name: Upload artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ante-static-musl-linux-x86_64
        path: target/x86_64-unknown-linux-musl/release/ante
